# dev: PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST:172.20.10.11}:${DB_PORT:30432}/${DB_NAME:app}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:app}
spring.datasource.password=${DB_PASSWORD:amwY7eypEv4n2PZFom3E2w3r3fqA8lEJMQ1PHkMNGUYzWbYlEYWnOIINmktP2EFq}

spring.datasource.hikari.maximum-pool-size=${DB_POOL_MAX:10}
spring.datasource.hikari.connection-timeout=30000

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.h2.console.enabled=false
